### PR TITLE
#769: Use an enum to detected the OS platform

### LINKED ISSUE #769: kamel cli download not working on windows
Extension version: 0.0.25

On windows, `getDownloadURLForCamelKTag` uses win32 as the platform name, but download links contain `windows-64bit` instead.

Since version checking is mandatory, the extension cannot start.

### PR DESCRIPTION
**Pull request by nanomad**
Use an enum to detected the OS platform

    Then decode it differently for kamel and kubectl.

    Fixes #769

### CODE REVIEW

**Comment by apupier** [comment]
CI build is blocked currently as @nanomad is unauthorized. Looking how to authorize the PR build

**Comment by apupier** [comment]
> CI build is blocked currently as @nanomad is unauthorized. Looking how to authorize the PR build

I click on "Rerun" and it allowed the build to kick-off. i think it will be fine for this time. Fo rfuture I can look further to add @nanomad to authorized users, especially if you plan to provide more Pull Requests :-)

File: src/versionUtils.ts [hunk 1]
```diff
@@ -197,7 +198,20 @@ function setVersionAndTellUser(msg: string, newVersion: string) {
...
+		case Platform.LINUX:
+			return 'linux';
+		case Platform.MACOS:
+			return 'mac';
+	}
+	return undefined;
+}
+
+export async function getDownloadURLForCamelKTag(camelKVersion : string, platform : Platform): Promise<string> {
+	let platformStr = toKamelOsString(platform);
```
Comment (apupier) [inline src/versionUtils.ts:214]: optional: better to use const as the value is nto changed after

**Review by apupier — APPROVED** [review]
Thanks for the fix!

remind for the rule of merging (so that's you're not surprised if it takes a bit of time):
* at least one maintainer has approved and no "request for change" and 24 hours since "Ready_for_review" label has been added
or
* all maintainers have approved

**Review by lhein — APPROVED** [review]

**Review by bfitzpat — APPROVED** [review]

File: src/versionUtils.ts (hunk 1 above)
Comment (nanomad) [reply src/versionUtils.ts]: Right!

**Comment by apupier** [comment]
thanks @nanomad
